### ISSUE TITLE
1.2.0 Release

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#140]
Please everyone leave a comment with a link to a pr or issue, so we have it tracked.

## TODO
- [x] PR with bump to `polkadot@1.5` https://github.com/polkadot-fellows/runtimes/pull/137 (minimal configurations, [just to compile](https://github.com/polkadot-fellows/runtimes/issues/101))
- [x] PR with bump to `polkadot-sdk@1.6.0` https://github.com/polkadot-fellows/runtimes/pull/159
- [x] PR with bump to `polkadot-sdk@1.7.0` https://github.com/polkadot-fellows/runtimes/pull/187
- [x] check/fix migrations when 1.1.0 / 1.1.2 deployed https://github.com/polkadot-fellows/runtimes/pull/195
- [x] regenerate weights
  - [x] regenerate weights for all pallets https://github.com/polkadot-fellows/runtimes/pull/223
    - [x] ping https://github.com/polkadot-fellows/runtimes/pull/187#issuecomment-1969253891
  - [x] check bridge transfer fee constants
- [x] bump spec_versions to `1_002_000` - done in https://github.com/polkadot-fellows/runtimes/pull/187
- [x] check and bump transaction versions https://github.com/polkadot-fellows/runtimes/issues/250
- [x] check Nacho's integration tests
  - [x] check/verify e2e tests: OpenGov -> relay to AssetHub - see [comment](https://github.com/polkadot-fellows/runtimes/pull/187/files#r1507284250) @muharem 
- [x] fix `#[api_version(7)] impl primitives::runtime_api::ParachainHost - fn node_features` + verify what is missing https://github.com/polkadot-fellows/runtimes/pull/194
- [x] add benchmark `cumulus_pallet_parachain_system` to SP runtimes
- [x] address comment [here](https://github.com/polkadot-fellows/runtimes/pull/57#issuecomment-1885008379)
- [x] integration tests improvement - adapt [comment](https://github.com/polkadot-fellows/runtimes/pull/114#discussion_r1420432244) fixed by https://github.com/polkadot-fellows/runtimes/pull/185
  ```
  # TODO: replace with `emulated-integration-tests-common@X.Y.Z` from `polkadot-sdk`
  integration-tests-common = { path = "../common" }
  ```
- [x] remove unneeded dependencies (`cargo machete`)
- [x] fix `pallet_asset_conversion benchmarks` https://github.com/paritytech/polkadot-sdk/issues/3440
- [x] Adds Snowbridge to Kusama and Polkadot Runtimes  https://github.com/polkadot-fellows/runtimes/pull/130

**Comment by bkchr** [comment]
> * check `try-runtime`- [ ]

This is done by CI. Or what you mean?

**Comment by bkontur** [comment]
> > * check `try-runtime`- [ ]
> 
> This is done by CI. Or what you mean?

ok, cool, thank you, removed from desc

**Comment by h4x3rotab** [comment]
Was it intended to keep Polkadot runtime version and the Polkadot SDK version `polkadot-vX.Y.Z`?

**Comment by bkontur** [comment]
@brenzi I am not touching encointer now, because iiuc, you need to release new versions of your crates with bumping them to `polkadot-sdk@1.5` first, right? So , we can align encointer afterwards. If you need any help, just tell me.


```
# encointer deps
encointer-balances-tx-payment = { default-features = false, version = "3.0.2" }
encointer-balances-tx-payment-rpc-runtime-api = { default-features = false, version = "3.0.2" }
encointer-primitives = { default-features = false, version = "3.0.2" }
pallet-encointer-balances = { default-features = false, version = "3.0.2" }
pallet-encointer-bazaar = { default-features = false, version = "3.0.2" }
pallet-encointer-bazaar-rpc-runtime-api = { default-features = false, version = "3.0.2" }
pallet-encointer-ceremonies = { default-features = false, version = "3.0.2" }
pallet-encointer-ceremonies-rpc-runtime-api = { default-features = false, version = "3.0.2" }
pallet-encointer-communities = { default-features = false, version = "3.0.2" }
pallet-encointer-communities-rpc-runtime-api = { default-features = false, version = "3.0.2" }
pallet-encointer-faucet = { default-features = false, version = "3.0.2" }
pallet-encointer-reputation-commitments = { default-features = false, version = "3.0.2" }
pallet-encointer-scheduler = { default-features = false, version = "3.0.2" }
```

**Comment by brenzi** [comment]
@bkontur let me check. We'd like to be part of the next release and will do the necessary

**Comment by bkontur** [comment]
> @bkontur let me check. We'd like to be part of the next release and will do the necessary

I guess, it is not a problem if you dont bump, encointer will just use old dependencies, 
it is more about to be up-to-date with latest stuff and be aligned with other SP runtimes

**Comment by bkchr** [comment]
> Was it intended to keep Polkadot runtime version and the Polkadot SDK version `polkadot-vX.Y.Z`?

I don't get the question?

> Also, when do we expect 1.2.0 to rollout?

Probably earliest around end of february.

**Comment by brenzi** [comment]
> it is more about to be up-to-date with latest stuff and be aligned with other SP runtimes

ok. do I get this right?:
* if we do nothing, our runtime will automatically be part of the next release and the corresponding whitelisting/referendum with spec version 1001000 
* if we upgrade dependencies, the spec version should be 1002000

**Comment by nanometerzhu** [comment]
> I don't get the question?

I think @h4x3rotab 's question is, even both polkadot-sdk and runtimes have same version format X.Y.Z, but looks like the numbers are different:

* runtime v1.0.0 -> polkadot-sdk v1.0.0
* runtime v1.1.0 -> polkadot-sdk v1.3.0
* runtime v1.2.0 -> polkadot-sdk v1.5.0

Is this unmatched a intended behavior? Is it possible to use same version number so the downstream teams can easier to track?

**Comment by bkchr** [comment]
> Is this unmatched a intended behavior?

Yes, fellowship is not following the release schedule etc of the `polkadot-sdk` repo. Most of the time the fellowship releases also include multiple `polkadot-sdk` releases.

> Is it possible to use same version number so the downstream teams can easier to track?

If required, we could probably track this in the CHANGELOG file.

**Comment by eskimor** [comment]
What is the timeline? Can we get coretime in, if everything is ready this week? We need two more PRs which are waiting for audit, so we would need to bump the polkadot-sdk release as well.

**Comment by bkchr** [comment]
We don't need audits for Kusama.

**Comment by liamaharon** [comment]
Can we include https://github.com/polkadot-fellows/runtimes/pull/122 in this release?

**Comment by bkontur** [comment]
> Can we include #122 in this release?

@liamaharon could this locks migration be related to the error bellow: 

for **Kusama:** https://github.com/polkadot-fellows/runtimes/actions/runs/7553599023/job/20564716882?pr=137
```
[2024-01-17T09:42:37Z ERROR runtime::executive] - 0. error: Failed to decode storage item `Balances::Locks`
[2024-01-17T09:42:37Z ERROR runtime::executive] - 1. error: Failed to decode storage item `Session::NextKeys`
```

unrelated to locks for **Polkadot**: https://github.com/polkadot-fellows/runtimes/actions/runs/7553599023/job/20564716569?pr=137
```
[2024-01-17T09:46:25Z ERROR runtime::executive] - 0. error: Failed to decode storage item `Proxy::Proxies`
```

a

**Comment by bkchr** [comment]
> I recall it is supposed to fix after a runtime upgrade, hopefully it self-resolves (@bkchr was that right?)

Which runtime upgrade? I think there are maybe still some broken keys in it. I don't remember us fixing this yet.

**Comment by liamaharon** [comment]
Fix for proxies @bkontur https://github.com/polkadot-fellows/runtimes/pull/150

@bkchr do you know what might be the issue with the session keys or should I take a look? polkadot has a `UpgradeSessionKeys` migration, maybe Kusama needs one too?

**Comment by acatangiu** [comment]
> Fix for proxies @bkontur #150
> 
> @bkchr do you know what might be the issue with the session keys or should I take a look? polkadot has a `UpgradeSessionKeys` migration, maybe Kusama needs one too?

Current `UpgradeSessionKeys` in Polkadot was added by https://github.com/polkadot-fellows/runtimes/pull/65 for adding BEEFY session keys - and will be removed once latest release containing it has been upgraded-into on-chain.

Kusama already went through that -  UpgradeSessionKeys` removed from Kusama in https://github.com/polkadot-fellows/runtimes/pull/73

**Comment by xlc** [comment]
We need to do https://github.com/paritytech/polkadot-sdk/issues/1323 to reduce the chance of bad values

**Comment by bkchr** [comment]
> @xlc this would only catch issues in tests, right? Not directly prevent on-chain issues?

The idea would be that we compile with `debug-asserts` enabled for when we build the binaries for `try-runtime`.

**Comment by joepetrowski** [comment]
- [ ] Add Asset Conversion to Polkadot Asset Hub (awaiting PR from @muharem ).
- [ ] If we update to Polkadot SDK v1.7.0 then we can also incorporate the Kusama People Chain.

**Comment by joepetrowski** [comment]
Here you go @xlc https://forum.polkadot.network/t/people-chain-launch-and-identity-migration-plan/5930

**Comment by xlc** [comment]
@bkchr sure I can try to help

I suggest we start making a standard release checklist from the questions I have

## Breaking Changes

- [ ] List all the breaking changes and identify the category (Tx version, Extrinsic usage (e.g. deprecate one in favor of another, XCM, runtime API, storage format, others)
- [ ] List all the relevant teams to notify and ensure they have acknowledged the breaking change.

## Testing

- [ ] List all the changes that need manual test and ensure they are tested using the release runtime. Ensure each change is tested and signed off.

## Post deployment

- [ ] List all the changes that require post deployment monitor (e.g. runtime migrations). Ensure each change is monitored and signed off after deployment.

## Appendix

Relevant teams:

- Parachains Teams: For all breaking changes
  - Someone list all the parachain teams here
- Wallet teams: For tx version and extrinsic usage breaking change
  - Someone list all the wallet teams here
- dApp teams: For extrinsic usage, XCM and storage format breaking change
  - Someone list all the dApp teams here, most likely both the parachain teams and wallet teams
- Indexer and block explorer teams: For storage format and XCM breaking change
  - Someone list all the indexer teams and block explorer teams here
- Validators
- Parachain collators
- RPC providers
- End users

---

Maybe someone at Parity DevRel team can help with the actual communication and check things off if we have determined there are breaking changes in this release.

And someone should go through the change log and determine if any of them may need manual test / extra test review and then we can do the work.

**Comment by bkchr** [comment]
> * List all the relevant teams to notify and ensure they have acknowledged the breaking change.

How should this work? We can not always wait for everybody to respond. This will drag everything completely down. I would also like to have more a pull approach from their side. Aka they pull the information instead that we need to push the information to them. I don't know why people always favor the push approach, because it is totally inefficient.

**Comment by h4x3rotab** [comment]
A pull approach is fine to me. It means we should have a central place to public the breaking change analysis, and wait for maybe at least 7 days for the relevant parties to comment. Only proceed if there's not significant problems.

**Comment by bkchr** [comment]
I asked that we finally use the `prdoc` system in `polkadot-sdk` to generate the changelogs. There are currently 4 or 5 audiences and the changes are explained for the relevant audiences. I would propose that everyone starts to monitor these to interrupt stuff early if needed.

**Comment by xlc** [comment]
How about mailing list? or something similar like matrix announcement channel. So that people can subscribe to topics relevant to them and receive notifications on updates instead of need to remember to check it every once a while

**Comment by bkchr** [comment]
Everything that doesn't require any human interaction for forwarding information is a good solution :D I mean you can get also something similar by subscribing to the polkadot-sdk/fellwowship-runtimes repo releases. If someone wants to write some page or whatever to do these announcements, let's do it!

**Comment by muharem** [comment]
small fixes: 
- [ ] https://github.com/polkadot-fellows/runtimes/pull/149
- [ ] https://github.com/polkadot-fellows/runtimes/pull/102

**Comment by bkontur** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/174

**Comment by bkontur** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/182

**Comment by nanometerzhu** [comment]
Hi all, do we have any estimate timeline of this release?

**Comment by bkontur** [comment]
Fellows, please review the "last" missing piece for this release, a bump to `polkadot-sdk@1.7.0`: https://github.com/polkadot-fellows/runtimes/pull/187

**Comment by xlc** [comment]
1.7.0 introduces XCM v4. there is no zero change it will introduce some XCM bugs and yet we still don’t have enough XCM e2e tests.

**Comment by acatangiu** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/130

also needed with priority in this release.

**Comment by eskimor** [comment]
Also: 
- [ ] #206 
- [ ] #215 
- [ ] #212 
- [ ] #205  

All but the coretime chain are ready, just waiting to be merged.

**Comment by joepetrowski** [comment]
Would like to have the Kusama People Chain launch:

- [ ] https://github.com/polkadot-fellows/runtimes/pull/217

**Comment by bkchr** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/161

**Comment by bkontur** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/229

**Comment by bkontur** [comment]
Weights were regenerated here: 
- [ ] https://github.com/polkadot-fellows/runtimes/pull/223

Also created two issues for big differences found:
- [ ] https://github.com/polkadot-fellows/runtimes/issues/230
- [ ] https://github.com/polkadot-fellows/runtimes/issues/231


cc: @eskimor you wanted to be pinged when new weighs are ready, so they are https://github.com/polkadot-fellows/runtimes/pull/223

**Comment by brenzi** [comment]
If possible, include this PR:
* [ ] https://github.com/polkadot-fellows/runtimes/pull/236

**Comment by joepetrowski** [comment]
> * [ ]  Add Asset Conversion to Polkadot Asset Hub (awaiting PR from @muharem ).
> * [x]  If we update to Polkadot SDK v1.7.0 then we can also incorporate the Kusama People Chain.

- [ ] https://github.com/polkadot-fellows/runtimes/pull/218
- [ ] https://github.com/polkadot-fellows/runtimes/pull/233

**Comment by s0me0ne-unkn0wn** [comment]
This one is totally ready and is only waiting for re-review of a single-line Changelog merge, and it would be really great to have it in the current release:

- [ ] #228 

An important one that must be merged before this release (otherwise, #178 must be reverted):

- [ ] #235

**Comment by alexggh** [comment]
- [ ] Bump pallet-authorithy-discovery to include https://github.com/paritytech/polkadot-sdk/pull/3733

**Comment by bkontur** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/245

**Comment by bkontur** [comment]
1.2.0 is almost ready, missing just:

From description:
- [ ] check and bump transaction versions
https://github.com/polkadot-fellows/runtimes/issues/250
- [ ] check Nacho's integration tests
  - [ ] check/verify e2e tests: OpenGov -> relay to AssetHub - see [comment](https://github.com/polkadot-fellows/runtimes/pull/187/files#r1507284250) @muharem

From comments:
- [ ] https://github.com/polkadot-fellows/runtimes/pull/245
- [ ] https://github.com/polkadot-fellows/runtimes/pull/233
- [ ] https://github.com/polkadot-fellows/runtimes/pull/212

**Comment by eskimor** [comment]
All of them look pretty ready! Let's get this done today! :rocket:

**Comment by acatangiu** [comment]
https://github.com/polkadot-fellows/runtimes/pull/245 needs rank3+ approval because it touched CI file

**Comment by eskimor** [comment]
> https://github.com/polkadot-fellows/runtimes/pull/245 needs rank3+ approval because it touched CI file

My approval still does not count. Anybody knows why?

**Comment by bkchr** [comment]
> My approval still does not count. Anybody knows why?

It did, please be patient with the CI :P

**Comment by bkchr** [comment]
> check Nacho's integration tests
> 
>     * [ ]  check/verify e2e tests: OpenGov -> relay to AssetHub - see [comment](https://github.com/polkadot-fellows/runtimes/pull/187/files#r1507284250) @muharem

@bkontur what is up with this?

**Comment by NachoPal** [comment]
Tests are green, but I had to comment `init_state_migration::InitMigrate` because I was getting the below error when trying to run Polkadot's runtime upgrade with Chopsticks. It is probably an issue with smoldot.

```
runtime::state-trie-migration DEBUG: [19993546] 🤖 running migrations on top of MigrationTask { top: To start, child: To start, dyn_top_items: 0, dyn_child_items: 0, dyn_size: 0, size: 0, top_items: 0, child_items: 0 } until MigrationLimits { size: 409600, item: 4800 }
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([5, 149, 38, 117, 134, 181, 119, 68, 146, 120, 132, 245, 25, 235, 129, 1, 78, 123, 144, 18, 9, 107, 65, 196, 235, 58, 175, 148, 127, 110, 164, 41], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 78, 123, 144, 18, 9, 107, 65, 196, 235, 58, 175, 148, 127, 110, 164, 41], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 83, 180, 18, 59, 46, 24, 110, 7, 251, 123, 173, 93, 218, 95, 85, 192], 512))
runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 180, 180, 157, 149, 50, 13, 144, 33, 153, 76, 133, 15, 37, 184, 227, 133], 512))
panicked at /Users/nacho/Desktop/PARITY/Repos/chopsticks/vendor/smoldot/lib/src/executor/storage_diff.rs:207:13:
assertion failed: in_parent_next_key > key

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:801:19)
    at wasm://wasm/00b1e282:wasm-function[1108]:0x191195
    at wasm://wasm/00b1e282:wasm-function[1334]:0x19979c
    at wasm://wasm/00b1e282:wasm-function[1318]:0x1992e0
    at wasm://wasm/00b1e282:wasm-function[245]:0x10b484
    at wasm://wasm/00b1e282:wasm-function[115]:0xba794
    at wasm://wasm/00b1e282:wasm-function[632]:0x16b359
    at wasm://wasm/00b1e282:wasm-function[1476]:0x19aeb1
    at __wbg_adapter_48 (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:384:10)
    at real (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:366:22)



node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/00b1e282:wasm-function[1108]:0x1912ab
    at wasm://wasm/00b1e282:wasm-function[1334]:0x19979c
    at wasm://wasm/00b1e282:wasm-function[1318]:0x1992e0
    at wasm://wasm/00b1e282:wasm-function[245]:0x10b484
    at wasm://wasm/00b1e282:wasm-function[115]:0xba794
    at wasm://wasm/00b1e282:wasm-function[632]:0x16b359
    at wasm://wasm/00b1e282:wasm-function[1476]:0x19aeb1
    at __wbg_adapter_48 (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:384:10)
    at real (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:366:22)
    at node:internal/process/task_queues:140:7
```

**Comment by bkchr** [comment]
> It is probably an issue with smoldot.

Yeah looks like one.

**Comment by bkontur** [comment]
> Tests are green, but I had to comment `init_state_migration::InitMigrate` because I was getting the below error when trying to run Polkadot's runtime upgrade with Chopsticks. It is probably an issue with smoldot.
> 
> ```
> runtime::state-trie-migration DEBUG: [19993546] 🤖 running migrations on top of MigrationTask { top: To start, child: To start, dyn_top_items: 0, dyn_child_items: 0, dyn_size: 0, size: 0, top_items: 0, child_items: 0 } until MigrationLimits { size: 409600, item: 4800 }
> runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([], 512))
> runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([5, 149, 38, 117, 134, 181, 119, 68, 146, 120, 132, 245, 25, 235, 129, 1, 78, 123, 144, 18, 9, 107, 65, 196, 235, 58, 175, 148, 127, 110, 164, 41], 512))
> runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 78, 123, 144, 18, 9, 107, 65, 196, 235, 58, 175, 148, 127, 110, 164, 41], 512))
> runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 83, 180, 18, 59, 46, 24, 110, 7, 251, 123, 173, 93, 218, 95, 85, 192], 512))
> runtime::state-trie-migration TRACE: [19993546] 🤖 migrated a top key, next_top_key = Some(BoundedVec([6, 222, 61, 138, 84, 210, 126, 68, 169, 213, 206, 24, 150, 24, 242, 45, 180, 180, 157, 149, 50, 13, 144, 33, 153, 76, 133, 15, 37, 184, 227, 133], 512))
> panicked at /Users/nacho/Desktop/PARITY/Repos/chopsticks/vendor/smoldot/lib/src/executor/storage_diff.rs:207:13:
> assertion failed: in_parent_next_key > key
> 
> Stack:
> 
> Error
>     at imports.wbg.__wbg_new_abda76e883ba8a5f (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:801:19)
>     at wasm://wasm/00b1e282:wasm-function[1108]:0x191195
>     at wasm://wasm/00b1e282:wasm-function[1334]:0x19979c
>     at wasm://wasm/00b1e282:wasm-function[1318]:0x1992e0
>     at wasm://wasm/00b1e282:wasm-function[245]:0x10b484
>     at wasm://wasm/00b1e282:wasm-function[115]:0xba794
>     at wasm://wasm/00b1e282:wasm-function[632]:0x16b359
>     at wasm://wasm/00b1e282:wasm-function[1476]:0x19aeb1
>     at __wbg_adapter_48 (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:384:10)
>     at real (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:366:22)
> 
> 
> 
> node:internal/event_target:1096
>   process.nextTick(() => { throw err; });
>                            ^
> Error [RuntimeError]: unreachable
>     at wasm://wasm/00b1e282:wasm-function[1108]:0x1912ab
>     at wasm://wasm/00b1e282:wasm-function[1334]:0x19979c
>     at wasm://wasm/00b1e282:wasm-function[1318]:0x1992e0
>     at wasm://wasm/00b1e282:wasm-function[245]:0x10b484
>     at wasm://wasm/00b1e282:wasm-function[115]:0xba794
>     at wasm://wasm/00b1e282:wasm-function[632]:0x16b359
>     at wasm://wasm/00b1e282:wasm-function[1476]:0x19aeb1
>     at __wbg_adapter_48 (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:384:10)
>     at real (file:///Users/nacho/Desktop/PARITY/Repos/chopsticks/executor/dist/esm/chopsticks_executor.js:366:22)
>     at node:internal/process/task_queues:140:7
> ```

@muharem @NachoPal so, can we consider these two points as done, or is anything missing?
- [ ] check Nacho's integration tests
  - [ ] check/verify e2e tests: OpenGov -> relay to AssetHub - see [comment](https://github.com/polkadot-fellows/runtimes/pull/187/files#r1507284250) @muharem

**Comment by NachoPal** [comment]
> we consider these two points as done

Yes, you can check the box

**Comment by kianenigma** [comment]
- [ ] we need to make sure that `pallet-staking` version `29.0.1` is released and used, which is the current version plus https://github.com/paritytech/polkadot-sdk/pull/3639 and (potentially one other patch).  This is basically making sure that the bug we fixed in 1.1.3 runtime release won't re-appear. Being worked on by @gpestana.

**Comment by bkontur** [comment]
> * [ ]  we need to make sure that `pallet-staking` version `29.0.1` is released and used, which is the current version plus [Staking ledger bonding fixes paritytech/polkadot-sdk#3639](https://github.com/paritytech/polkadot-sdk/pull/3639) and (potentially one other patch).  This is basically making sure that the bug we fixed in 1.1.3 runtime release won't re-appear. Being worked on by @gpestana.

So, it looks like everything is marked as done, and this is the last thing.

**One question or point: do we want to regenerate fresh weights once more?**

I did it for all runtimes [here](https://github.com/polkadot-fellows/runtimes/pull/223) based on `main` branch commit [`f5aeb7e8cc024a17a42ca547645f25f2ae28e4f4` commit](https://github.com/polkadot-fellows/runtimes/commit/f5aeb7e8cc024a17a42ca547645f25f2ae28e4f4) and after that I also did fresh weights for `people-kusama` / `coretime-kusama` and Snowbridge pallets.

I'm just bringing this to your attention because last time it took somewhere between 12 to 23 hours on Oliver's machine (Kusama/Polkadot are the slowest - several hours, while SPs are fast). Maybe there's no need to regenerate for all runtimes, and we could just regenerate for the concrete pallets affected after commit `f5aeb7e8cc024a17a42ca547645f25f2ae28e4f4`?

I can see just these candidates:
```
pallet_state_trie_migration
pallet_asset_conversion
pallet_treasury
pallet_staking
```

E.g. is this ok? https://github.com/polkadot-fellows/runtimes/commit/360581ffedd048262177ddc135d66cec455b959a#diff-e7afb81f3cef77f8a1686085f1adaa992122790270bae77eb2e640ad40b12cf4R1560-R1561
```
	// Use same weights as substrate ones.
	type WeightInfo = pallet_state_trie_migration::weights::SubstrateWeight<Runtime>;
```

**Comment by ggwpez** [comment]
> I'm just bringing this to your attention because last time it took somewhere between 12 to 23 hours on Oliver's machine (Kusama/Polkadot are the slowest - several hours, while SPs are fast). Maybe there's no need to regenerate for all runtimes, and we could just regenerate for the concrete pallets affected after commit `f5aeb7e8cc024a17a42ca547645f25f2ae28e4f4`?

I think we used the same weights for the state-trie-migration as on Kusama? So should be fine.  
For the other pallet, yea we *could* regenerate if its quick, but would not want to hold up the release for it.

**Comment by bkontur** [comment]
> > I'm just bringing this to your attention because last time it took somewhere between 12 to 23 hours on Oliver's machine (Kusama/Polkadot are the slowest - several hours, while SPs are fast). Maybe there's no need to regenerate for all runtimes, and we could just regenerate for the concrete pallets affected after commit `f5aeb7e8cc024a17a42ca547645f25f2ae28e4f4`?
> 
> I think we used the same weights for the state-trie-migration as on Kusama? So should be fine. For the other pallet, yea we _could_ regenerate if its quick, but would not want to hold up the release for it.

ok, I just did `pallet_asset_conversion` and `pallet_treasury`:
- [ ] https://github.com/polkadot-fellows/runtimes/pull/256

**Comment by acatangiu** [comment]
should we close this now?

**Comment by bkontur** [comment]
1.2.0 is released: https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.0, next https://github.com/polkadot-fellows/runtimes/issues/186
