### ISSUE TITLE
1.3.0 Release

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#186]
## TODO for removing older stuff

- [x] DMPQueue https://github.com/polkadot-fellows/runtimes/pull/137#issuecomment-1893483027
  - [x] remove pallet https://github.com/polkadot-fellows/runtimes/pull/280
   ```
   impl cumulus_pallet_dmp_queue::Config
   ...
   DmpQueue: cumulus_pallet_dmp_queue = XY,
   ```
  - [x] clean storage data (add migration or `kill_storage`) https://github.com/polkadot-fellows/runtimes/pull/280
- [x] remove duplicated `check_sane_fees_values` / `diff_as_percent` when `polkadot-sdk@1.8.0`
- [x] remove hack for skipping `check-migrations` for Encointer (based on https://github.com/polkadot-fellows/runtimes/pull/159#issuecomment-1966836443)
- [x] remove `penpal-runtime-dotsama` and instead fix like [this](https://github.com/paritytech/polkadot-sdk/pull/3564) when `polakdot-sdk@1.9.0`
- [x] fix https://github.com/polkadot-fellows/runtimes/issues/234
- [x] check `runtimes-matrix.json` and add `uri` for `people-kusama` and `coretime-kusama` - https://github.com/polkadot-fellows/runtimes/pull/425
- [x] ~~remove `helpers` module from inegrations-tests and re-use from `polkadot-sdk` https://github.com/polkadot-fellows/runtimes/issues/363~~

**Comment by bkchr** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/issues/248

**Comment by eskimor** [comment]
- [ ] Make sure [this](https://github.com/paritytech/polkadot-sdk/pull/3714) gets in. Either by using upcoming polkadot-sdk 1.10.0 or backporting 4714.

**Comment by bkchr** [comment]
- Coretime, depending on how the migration works on Kusama

**Comment by s0me0ne-unkn0wn** [comment]
- [ ] Bump version of `bh-bridge-hub-cumulus` to at least 0.10.0
- [ ] Remove transient code introduced by [this commit](https://github.com/polkadot-fellows/runtimes/pull/266/commits/2f3a1ccadd79eedac24bd2df2781a90ef7e0975d)

**Comment by joepetrowski** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/269

**Comment by rossbulat** [comment]
I've noticed `pallet-staking` has been bumped to 29.0.2 in the workspace, but just wanted to check https://github.com/paritytech/polkadot-sdk/pull/2589 will be deployed in 1.3.0 as to move forward with controller account deprecation.

**Comment by s0me0ne-unkn0wn** [comment]
- [ ] #266

**Comment by joepetrowski** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/356
- [ ] https://github.com/paritytech/polkadot-sdk/pull/4778
- [ ] https://github.com/polkadot-fellows/runtimes/pull/322 (at least)
- [ ] https://github.com/paritytech/polkadot-sdk/pull/4527 (nice to have)

**Comment by the-right-joyce** [comment]
- [ ] Add Integritee's lease to the coretime migration

**Comment by bkchr** [comment]
> * [ ]  Add Integritee's lease to the coretime migration

@the-right-joyce is there more information on this?

**Comment by joepetrowski** [comment]
^I think we should just change it to, "Include migration for all existing parachains to coretime"

**Comment by SBalaguer** [comment]
> > * [ ]   Add Integritee's lease to the coretime migration
> 
> @the-right-joyce is there more information on this?

@bkchr the biggest problem is that the current auction model allows for chains to have 'future' leases (a.k.a. a lease that starts sometime in the future) and the new coretime model does not (a.k.a. teams can't have a core that starts in the future, it needs to start now and for a given amount of time). Therefore we need to find a solution to make these two things work.

If the migration takes a snapshot of the system at a given point in time, it will find:
- Parachains that currently hold a slot for a given amount of time.
- Parachains that don't have a slot currently and have one starting sometime in the future. This future can be anything from the immediate next lease period, up to 7 lease periods in the future (~1y).

What I would suggest then, is to compromise on giving a core to every team that either currently has a slot now, or that has a slot starting in the upcoming lease period. From my point of view, migrating this way would make it more compatible with the current auctions happening on Polkadot. This would mean giving 'free coretime' to the teams that start in the upcoming lease period (which with current estimates of launch is ~1mo).

**Example: Integritee**
Integritee has been a parachain on Polkadot since August 2022 when [they won auction #23](https://parachains.info/auctions/polkadot-19-25), which gave them a slot that expired on LP17. Unfortunately, this team didn't manage to secure an auction that would allow them to have a slot for LP17, yet they did [win auction 69](https://parachains.info/auctions/polkadot-67-73) that granted them a lease for LP18-24.

If the migration of coretime happens anytime during LP17 (as it's expected) and it only considers teams holding a lease, then Integritee would be left without a core. However, if we pursue a migration as I'm suggesting by which every team that has a slot now, or has one starting on LP18 gets a core, then Integritee would be having a core.

**Open Questions**
The biggest item to discuss potentially on this is load (i.e.: having more cores allocated in the future than the current amount of slots). I don't see this as a potentially big issue as the new teams that win an auction in the current set of auctions would replace those that don't manage to extend their lease, but might be worth it to double-check the numbers.

**Comment by eskimor** [comment]
- [ ] Enable Coretime on the relay chain

**Comment by brenzi** [comment]
@bkchr I'm obviously biased here, but Integritee has won an auction at a certain price for a range of lease periods. What you suggest is breaking this "contract", leaving Integritee worse off (just to avoid technical extra work by the fellowship for the migration). Kusama had no similar case AFAIK.

Let me just suggest the most simple possible solution: Grant Integritee a few weeks of coretime ahead of their official lease LP18 and save a lot of hassle (migrate as if it was active in LP17). With all the usual delays to be expected, this will make very little difference for anyone. Integritee's DOT are locked already anyway.

**Comment by eskimor** [comment]
@brenzi I am looking into it, but to explain the reasoning: The original assumption was, that if a lease has not yet started, then we are also not causing any liveness issues, so refunding and going directly with Coretime should be acceptable and seemed like the fairest solution at the time. (E.g. otherwise people could buy part time leases on purpose to get free coretime.)

**Comment by seadanda** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/401
- [ ] https://github.com/polkadot-fellows/runtimes/pull/410

**Comment by eskimor** [comment]
- [ ] Run benchmarks
- [ ] Final tests (with finalized weights)

**Comment by skunert** [comment]
This should go in too: https://github.com/polkadot-fellows/runtimes/pull/423

**Comment by seadanda** [comment]
Last bits before triggering the release:
- [ ] https://github.com/polkadot-fellows/runtimes/pull/434
- [ ] https://github.com/polkadot-fellows/runtimes/pull/426
- [ ] https://github.com/polkadot-fellows/runtimes/pull/433
- [ ] https://github.com/paritytech/polkadot-sdk/pull/5369 bump when released to crates

**Comment by olanod** [comment]
It would be nice to get this small Kusama addition https://github.com/polkadot-fellows/runtimes/pull/430

**Comment by joepetrowski** [comment]
> It would be nice to get this small Kusama addition #430

It was merged so it is in.
