### ISSUE TITLE
Encointer checks/improvements

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#199]
## Check or fix

- [ ] setup `FeeManager` according to other SP parachains, is it ok to have it like `type FeeManager = ();` ?
- [x] `type IsReserve = NativeAsset;` - do other chains send `ReserveAssetDeposited` to Encointer?

## TODO

- [x] setup `pallet_xcm` benchmarks and replace `type WeightInfo = pallet_xcm::TestWeightInfo;`

cc: @brenzi

**Comment by brenzi** [comment]
yea, plz. assign this to me

**Comment by bkontur** [comment]
@brenzi I cannot assign, don't you have "assing yourself" button there?
I guess nobody won't work on this :)

**Comment by bkontur** [comment]
@brenzi can you also please this PR https://github.com/bkontur/runtimes/pull/4 and review/approve? It contains your changes plus few my nits.

**Comment by bkontur** [comment]
@brenzi When do you think you could check this? At the very least, setting up `pallet_xcm` benchmarks would be very useful.

**Comment by brenzi** [comment]
We'll take care within the next 4 weeks, among other related pending tasks for the runtime.
I suggest not to wait for this for the release 1.2.0

**Comment by brenzi** [comment]
this will be easier to fix after the cleanup in https://github.com/polkadot-fellows/runtimes/pull/270

**Comment by clangenb** [comment]
Is anything still open here?

**Comment by bkontur** [comment]
@brenzi what about this older one?

**Comment by brenzi** [comment]
the point on `FeeAsset` can be resolved I guess. 

the `IsReserve` I'm not sure of there is need to change anything now. 

> do other chains send ReserveAssetDeposited to Encointer?
`IsReserve` is just a copy paste. All we need to be able to do currently is teleport KSM to/from relay or AssetHub. I have no strong opinion otherwise. Do you have a suggestion here?

The last point is still open: We don't have custom benchmarking for XCM yet

**Comment by brenzi** [comment]
I think this can be closed after #440

**Comment by clangenb** [comment]
@bkontur this can be closed now.
