### ISSUE TITLE
[Tracker] [Nomination Pools] Enabling Opengov voting support for Nomination Pool members

### ISSUE THREAD

**Issue by Ank4n** [polkadot-fellows/runtimes#455]
Moved from: https://github.com/paritytech/polkadot-sdk/issues/5659

[polkadot-sdk/stable2409](https://github.com/paritytech/polkadot-sdk/issues/5583) release contains fixes post which Nomination Pool can switch to `DelegateStake` strategy. This will then allow Nomination Pool members to vote in opengov with their pooled funds.

## Expected timeline
- [polkadot-sdk/stable2409](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-stable2409) released on Sept 26, 2024. 
- **[Updated on 11th October]**: The referendum for Kusama and Polkadot runtime upgrade is expected to be [proposed by end of October](https://github.com/polkadot-fellows/runtimes/issues/469). Decision period for Kusama and Polkadot can be upto 14 and 28 days respectively.

## Checklist
- [x] `stable2409` SDK release.
- [x] Runtime upgrade referendum.
- [x] Runtime config changes and migration for Kusama and Polkadot. Refer [westend runtime changes](https://github.com/paritytech/polkadot-sdk/pull/3905/files#diff-5264d812f7aadfc486efffd3322b11c8dee5e8ddf2e77e0a9e70b573f3d2afddR1373).
- [x] Migrate all pool members permissionlessly post runtime upgrade.

**Comment by kianenigma** [comment]
@anaelleltd can you please pin this issue?
