### ISSUE TITLE
Reduce Snowbridge Fees

### ISSUE THREAD

**Issue by vgeddes** [polkadot-fellows/runtimes#503]
This is a request for the fellowship to whitelist a Snowbridge governance preimage. When executed, it will reduce snowbridge fees for users.

I've already submitted the necessary [preimage](https://polkadot.subscan.io/preimage/0xa1121009c8fe5d479bd58debacf38c8fba87b2e280c9f03cff1d06d99860b7d6) on the relay and collectives chain.

Could the fellowship please create a fellowship referendum using the following call. I don't have the necessary privileges:
```
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e0202afb477613058cad73e5bc7d244987bfe48b18208b703e3196e2ef5659f6e0fc835000000010a000000
```

## Details

The proposal executes the following:

1. Updates AH with a new Polkadot->Ethereum base fee of 1.49 DOT. Or more plainly, users will only need to pay 1.49 DOT to send messages to Ethereum.
3. Updates BH with new pricing parameters:
  * ExchangeRate: 0.002288329519450801 ETH/DOT
  * FeePerGas: 10.000000000 GWEI

## Artifacts

The preimage was generated using our governance tooling:
```
cargo run --features polkadot --bin snowbridge-preimage -- pricing-parameters --exchange-rate-numerator 1 --exchange-rate-denominator 437 --multiplier-numerator 1  --multiplier-denominator 1  --fee-per-gas 10  --local-reward 0.01  --remote-reward 0.00025
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/snowbridge-preimage pricing-parameters --exchange-rate-numerator 1 --exchange-rate-denominator 437 --multiplier-numerator 1 --multiplier-denominator 1 --fee-per-gas 10 --local-reward 0.01 --remote-reward 0.00025`
BridgeHub:
  ExchangeRate: 0.002288329519450801 ETH/DOT
  FeePerGas: 10.000000000 GWEI
  LocalReward: 0.0100000000 DOT [100000000 PLANCK]
  RemoteReward: 0.000250000000000000 ETH [250000000000000 WEI]
AssetHub:
  BaseFee: 1.4929540998 DOT, [14929540998 PLANCK]
Storage key for 'BridgeHubEthereumBaseFee': 0x5fbc5c7ba58845ad1f1a9a7c5bc12fad
Preimage Hash: 0x8083e29930deaddd690c01f53456149bfbce2ea6f8d06a16f1b1c320d6a3c743
Preimage Size: 202
0x1a0208630003000100a90f030c2f00000602b25ec1b65946c9015302b1ca223c39210800000000000000000000e1f50500000000000000000000000000a031a95fe3000000000000000000000000000000000000000000000000000000e40b5402000000000000000000000000000000000000000000000000000000000064a7b3b6e00d00000000000000002000630003000100a10f030c2f000006025e45e4240094000404405fbc5c7ba58845ad1f1a9a7c5bc12fad4086b7de790300000000000000000000002000
```

And then run through `opengov-cli`:
```
Submit the preimage for the Fellowship referendum:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b00d41f0004010004082f0000060342c78b76216f8817008083e29930deaddd690c01f53456149bfbce2ea6f8d06a16f1b1c320d6a3c743

Open a Fellowship referendum to whitelist the call:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e0202afb477613058cad73e5bc7d244987bfe48b18208b703e3196e2ef5659f6e0fc835000000010a000000

Submit the preimage for the public referendum:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-rpc.dwellir.com#/extrinsics/decode/0x0a00310317031a0208630003000100a90f030c2f00000602b25ec1b65946c9015302b1ca223c39210800000000000000000000e1f50500000000000000000000000000a031a95fe3000000000000000000000000000000000000000000000000000000e40b5402000000000000000000000000000000000000000000000000000000000064a7b3b6e00d00000000000000002000630003000100a10f030c2f000006025e45e4240094000404405fbc5c7ba58845ad1f1a9a7c5bc12fad4086b7de790300000000000000000000002000

Open a public referendum to dispatch the call:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-rpc.dwellir.com#/extrinsics/decode/0x1500160d02a1121009c8fe5d479bd58debacf38c8fba87b2e280c9f03cff1d06d99860b7d6cc0000000164000000

Batch to submit on Polkadot Relay Chain:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-rpc.dwellir.com#/extrinsics/decode/0x1a04080a00310317031a0208630003000100a90f030c2f00000602b25ec1b65946c9015302b1ca223c39210800000000000000000000e1f50500000000000000000000000000a031a95fe3000000000000000000000000000000000000000000000000000000e40b5402000000000000000000000000000000000000000000000000000000000064a7b3b6e00d00000000000000002000630003000100a10f030c2f000006025e45e4240094000404405fbc5c7ba58845ad1f1a9a7c5bc12fad4086b7de7903000000000000000000000020001500160d02a1121009c8fe5d479bd58debacf38c8fba87b2e280c9f03cff1d06d99860b7d6cc0000000164000000

Batch to submit on Polkadot Collectives Chain:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2804082b00d41f0004010004082f0000060342c78b76216f8817008083e29930deaddd690c01f53456149bfbce2ea6f8d06a16f1b1c320d6a3c7433d003e0202afb477613058cad73e5bc7d244987bfe48b18208b703e3196e2ef5659f6e0fc835000000010a000000
```

## Tasks
- [x] Submit the preimage for the Fellowship referendum
- [x] Submit the preimage for the public referendum
- [ ] Open a Fellowship referendum to whitelist the call

**Comment by acatangiu** [comment]
@vgeddes I checked the calls and everything looks good except the following questions:

1. how can one validate the raw storage changes on AH?
![Screenshot 2024-12-17 at 12 59 55](https://github.com/user-attachments/assets/8b8721cf-00cc-4f55-8ac9-cb91e7006fbe)
please add an `ensure_root()` call to change this in the future - setting storage directly is obfuscated and error-prone.
2. did you execute/simulate this referenda under chopsticks to make sure everything executed successfully (avoid silly failures like wrong weight-limits for example)?

**Comment by vgeddes** [comment]
Looks like we're going to substitute this proposal with another one that does a few other operations too. Going to close this one off.

Yeah the raw storage change is not great. In the longer-term it is no longer necessary with Snowbridge V2.

In the short-term, we could add a pallet to AH to change the storage. However, given that this requires a polkadot-sdk backport and runtime upgrade, it is more of a medium-term solution.

**Comment by acatangiu** [comment]
> In the short-term, we could add a pallet to AH to change the storage. However, given that this requires a polkadot-sdk backport and runtime upgrade, it is more of a medium-term solution.

You should also consider using [dynamic parameters](https://github.com/paritytech/polkadot-sdk/pull/2061) so that you can change them without doing raw `set_storage()`.

> Looks like we're going to substitute this proposal with another one that does a few other operations too. Going to close this one off.

For the substitute proposal, if you'll use `set_storage()`, the same question will stand: how can one validate the correctness of its parameters? How did you arrive at the storage key value - so we can independently verify we arrive at the same key value then can also verify it's proposed new value.
